// ==================== Encoded Exercise Database ====================
// Exercises are base64 encoded to prevent casual viewing of answers
const ENCODED_EXERCISES =
  "ewogICAgImdyYW1tYXIiOiBbCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiSmEgX19fICh0byBlYXQpIGphYsWCa28uIiwKICAgICAgICAgICAgImFuc3dlciI6ICJqZW0iLAogICAgICAgICAgICAidG9waWMiOiAiZ3JhbW1hciIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlR5IF9fXyAodG8gcmVhZCkga3NpxIXFvGvEmS4iLAogICAgICAgICAgICAiYW5zd2VyIjogImN6eXRhc3oiLAogICAgICAgICAgICAidG9waWMiOiAiZ3JhbW1hciIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIk9uIF9fXyAodG8gd3JpdGUpIGxpc3QuIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwaXN6ZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJncmFtbWFyIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiTXkgX19fICh0byBzcGVhaykgcG8gcG9sc2t1LiIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibcOzd2lteSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJncmFtbWFyIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiT25pIF9fXyAodG8gaGF2ZSkgZG9tLiIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibWFqxIUiLAogICAgICAgICAgICAidG9waWMiOiAiZ3JhbW1hciIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkphIF9fXyAodG8gc2xlZXApIGRvYnJ6ZS4iLAogICAgICAgICAgICAiYW5zd2VyIjogIsWbcGnEmSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJncmFtbWFyIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiT25hIF9fXyAodG8gZHJpbmspIHdvZMSZLiIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicGlqZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJncmFtbWFyIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiV3kgX19fICh0byBrbm93KSBvZHBvd2llZMW6LiIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAid2llY2llIiwKICAgICAgICAgICAgInRvcGljIjogImdyYW1tYXIiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJKYSBfX18gKHRvIGxvdmUpIG11enlrxJkuIiwKICAgICAgICAgICAgImFuc3dlciI6ICJrb2NoYW0iLAogICAgICAgICAgICAidG9waWMiOiAiZ3JhbW1hciIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlR5IF9fXyAodG8gd29yaykgdyBiaXVyemUuIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwcmFjdWplc3oiLAogICAgICAgICAgICAidG9waWMiOiAiZ3JhbW1hciIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIk9uYSBfX18gKHRvIHN0dWR5KSBtZWR5Y3luxJkuIiwKICAgICAgICAgICAgImFuc3dlciI6ICJzdHVkaXVqZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJncmFtbWFyIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiTXkgX19fICh0byBnbykgZG8ga2luYS4iLAogICAgICAgICAgICAiYW5zd2VyIjogImlkemllbXkiLAogICAgICAgICAgICAidG9waWMiOiAiZ3JhbW1hciIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIk9uaSBfX18gKHRvIHBsYXkpIHcgcGnFgmvEmS4iLAogICAgICAgICAgICAiYW5zd2VyIjogImdyYWrEhSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJncmFtbWFyIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiSmEgX19fICh0byB3YW50KSBrYXfEmS4iLAogICAgICAgICAgICAiYW5zd2VyIjogImNoY8SZIiwKICAgICAgICAgICAgInRvcGljIjogImdyYW1tYXIiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUeSBfX18gKHRvIHVuZGVyc3RhbmQpIHRvPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicm96dW1pZXN6IiwKICAgICAgICAgICAgInRvcGljIjogImdyYW1tYXIiCiAgICAgICAgfQogICAgXSwKICAgICJudW1iZXJzIjogWwogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldyaXRlIDUgaW4gUG9saXNoIChvcmRpbmFsKSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicGnEhXR5IiwKICAgICAgICAgICAgInRvcGljIjogIm51bWJlcnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXcml0ZSAxMCBpbiBQb2xpc2ggKGNhcmRpbmFsKSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZHppZXNpxJnEhyIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJudW1iZXJzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiV3JpdGUgMjMgaW4gUG9saXNoIChjYXJkaW5hbCkiLAogICAgICAgICAgICAiYW5zd2VyIjogImR3YWR6aWXFm2NpYSB0cnp5IiwKICAgICAgICAgICAgInRvcGljIjogIm51bWJlcnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXcml0ZSAxc3QgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwaWVyd3N6eSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJudW1iZXJzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiV3JpdGUgMTAwIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAic3RvIiwKICAgICAgICAgICAgInRvcGljIjogIm51bWJlcnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXcml0ZSAzcmQgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJ0cnplY2kiLAogICAgICAgICAgICAidG9waWMiOiAibnVtYmVycyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldyaXRlIDcgaW4gUG9saXNoIChjYXJkaW5hbCkiLAogICAgICAgICAgICAiYW5zd2VyIjogInNpZWRlbSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJudW1iZXJzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiV3JpdGUgMm5kIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZHJ1Z2kiLAogICAgICAgICAgICAidG9waWMiOiAibnVtYmVycyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldyaXRlIDE1IGluIFBvbGlzaCAoY2FyZGluYWwpIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwacSZdG5hxZtjaWUiLAogICAgICAgICAgICAidG9waWMiOiAibnVtYmVycyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldyaXRlIDUwIGluIFBvbGlzaCAoY2FyZGluYWwpIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwacSZxIdkemllc2nEhXQiLAogICAgICAgICAgICAidG9waWMiOiAibnVtYmVycyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldyaXRlIDR0aCBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogImN6d2FydHkiLAogICAgICAgICAgICAidG9waWMiOiAibnVtYmVycyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldyaXRlIDEyIGluIFBvbGlzaCAoY2FyZGluYWwpIiwKICAgICAgICAgICAgImFuc3dlciI6ICJkd2FuYcWbY2llIiwKICAgICAgICAgICAgInRvcGljIjogIm51bWJlcnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXcml0ZSAyMCBpbiBQb2xpc2ggKGNhcmRpbmFsKSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZHdhZHppZcWbY2lhIiwKICAgICAgICAgICAgInRvcGljIjogIm51bWJlcnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXcml0ZSA2dGggaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJzesOzc3R5IiwKICAgICAgICAgICAgInRvcGljIjogIm51bWJlcnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXcml0ZSAxMDAwIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAidHlzacSFYyIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJudW1iZXJzIgogICAgICAgIH0KICAgIF0sCiAgICAiY2FzZXMiOiBbCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiSSBzZWUgYSBfX18gKGRvZyAtIGFjY3VzYXRpdmUpIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwc2EiLAogICAgICAgICAgICAidG9waWMiOiAiY2FzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJJIGdpdmUgdG8gX19fIChtb3RoZXIgLSBkYXRpdmUpIiwKICAgICAgICAgICAgImFuc3dlciI6ICJtYXRjZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJjYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldpdGggX19fIChmcmllbmQgLSBpbnN0cnVtZW50YWwpIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwcnp5amFjaWVsZW0iLAogICAgICAgICAgICAidG9waWMiOiAiY2FzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJBYm91dCBfX18gKGJvb2sgLSBsb2NhdGl2ZSkiLAogICAgICAgICAgICAiYW5zd2VyIjogImtzacSFxbxjZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJjYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldpdGhvdXQgX19fICh3YXRlciAtIGdlbml0aXZlKSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAid29keSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJjYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIl9fXyAoY2F0IC0gbm9taW5hdGl2ZSkgaXMgc2xlZXBpbmciLAogICAgICAgICAgICAiYW5zd2VyIjogImtvdCIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJjYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkkgc2VlIF9fXyAod29tYW4gLSBhY2N1c2F0aXZlKSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAia29iaWV0xJkiLAogICAgICAgICAgICAidG9waWMiOiAiY2FzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJJIGdpdmUgdG8gX19fIChmYXRoZXIgLSBkYXRpdmUpIiwKICAgICAgICAgICAgImFuc3dlciI6ICJvamN1IiwKICAgICAgICAgICAgInRvcGljIjogImNhc2VzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiV2l0aCBfX18gKHBlbiAtIGluc3RydW1lbnRhbCkiLAogICAgICAgICAgICAiYW5zd2VyIjogImTFgnVnb3Bpc2VtIiwKICAgICAgICAgICAgInRvcGljIjogImNhc2VzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiQWJvdXQgX19fIChjaXR5IC0gbG9jYXRpdmUpIiwKICAgICAgICAgICAgImFuc3dlciI6ICJtaWXFm2NpZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJjYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldpdGhvdXQgX19fIChtb25leSAtIGdlbml0aXZlKSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicGllbmnEmWR6eSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJjYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkkgaGF2ZSBfX18gKGJyb3RoZXIgLSBhY2N1c2F0aXZlKSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiYnJhdGEiLAogICAgICAgICAgICAidG9waWMiOiAiY2FzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJJIHdyaXRlIF9fXyAoc2lzdGVyIC0gZGF0aXZlKSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAic2lvc3RyemUiLAogICAgICAgICAgICAidG9waWMiOiAiY2FzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJJIGVhdCB3aXRoIF9fXyAoZm9yayAtIGluc3RydW1lbnRhbCkiLAogICAgICAgICAgICAiYW5zd2VyIjogIndpZGVsY2VtIiwKICAgICAgICAgICAgInRvcGljIjogImNhc2VzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiSW4gX19fIChzY2hvb2wgLSBsb2NhdGl2ZSkiLAogICAgICAgICAgICAiYW5zd2VyIjogInN6a29sZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJjYXNlcyIKICAgICAgICB9CiAgICBdLAogICAgInZvY2FidWxhcnkiOiBbCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlOiBrb3QiLAogICAgICAgICAgICAiYW5zd2VyIjogImNhdCIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2b2NhYnVsYXJ5IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlOiBkb20iLAogICAgICAgICAgICAiYW5zd2VyIjogImhvdXNlIiwKICAgICAgICAgICAgInRvcGljIjogInZvY2FidWxhcnkiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGU6IHdvZGEiLAogICAgICAgICAgICAiYW5zd2VyIjogIndhdGVyIiwKICAgICAgICAgICAgInRvcGljIjogInZvY2FidWxhcnkiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGU6IGtzacSFxbxrYSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiYm9vayIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2b2NhYnVsYXJ5IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlOiBkemllxYQiLAogICAgICAgICAgICAiYW5zd2VyIjogImRheSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2b2NhYnVsYXJ5IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlOiBub2MiLAogICAgICAgICAgICAiYW5zd2VyIjogIm5pZ2h0IiwKICAgICAgICAgICAgInRvcGljIjogInZvY2FidWxhcnkiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGU6IG1pxYJvxZvEhyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibG92ZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2b2NhYnVsYXJ5IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlOiBwcnp5amHFusWEIiwKICAgICAgICAgICAgImFuc3dlciI6ICJmcmllbmRzaGlwIiwKICAgICAgICAgICAgInRvcGljIjogInZvY2FidWxhcnkiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGU6IHBpZXMiLAogICAgICAgICAgICAiYW5zd2VyIjogImRvZyIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2b2NhYnVsYXJ5IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlOiBva25vIiwKICAgICAgICAgICAgImFuc3dlciI6ICJ3aW5kb3ciLAogICAgICAgICAgICAidG9waWMiOiAidm9jYWJ1bGFyeSIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZTogZHJ6d2kiLAogICAgICAgICAgICAiYW5zd2VyIjogImRvb3IiLAogICAgICAgICAgICAidG9waWMiOiAidm9jYWJ1bGFyeSIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZTogc3TDs8WCIiwKICAgICAgICAgICAgImFuc3dlciI6ICJ0YWJsZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2b2NhYnVsYXJ5IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlOiBrcnplc8WCbyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiY2hhaXIiLAogICAgICAgICAgICAidG9waWMiOiAidm9jYWJ1bGFyeSIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZTogc2Ftb2Now7NkIiwKICAgICAgICAgICAgImFuc3dlciI6ICJjYXIiLAogICAgICAgICAgICAidG9waWMiOiAidm9jYWJ1bGFyeSIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZTogcm93ZXIiLAogICAgICAgICAgICAiYW5zd2VyIjogImJpY3ljbGUiLAogICAgICAgICAgICAidG9waWMiOiAidm9jYWJ1bGFyeSIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZTogc3prb8WCYSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAic2Nob29sIiwKICAgICAgICAgICAgInRvcGljIjogInZvY2FidWxhcnkiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGU6IHByYWNhIiwKICAgICAgICAgICAgImFuc3dlciI6ICJ3b3JrIiwKICAgICAgICAgICAgInRvcGljIjogInZvY2FidWxhcnkiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGU6IHJvZHppbmEiLAogICAgICAgICAgICAiYW5zd2VyIjogImZhbWlseSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2b2NhYnVsYXJ5IgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlOiBtYXRrYSIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibW90aGVyIiwKICAgICAgICAgICAgInRvcGljIjogInZvY2FidWxhcnkiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGU6IG9qY2llYyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZmF0aGVyIiwKICAgICAgICAgICAgInRvcGljIjogInZvY2FidWxhcnkiCiAgICAgICAgfQogICAgXSwKICAgICJ2ZXJicyI6IFsKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJDb25qdWdhdGUgJ2J5xIcnICh0byBiZSkgZm9yICdqYSciLAogICAgICAgICAgICAiYW5zd2VyIjogImplc3RlbSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2ZXJicyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkNvbmp1Z2F0ZSAnbWllxIcnICh0byBoYXZlKSBmb3IgJ3R5JyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibWFzeiIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2ZXJicyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkNvbmp1Z2F0ZSAnacWbxIcnICh0byBnbykgZm9yICdvbiciLAogICAgICAgICAgICAiYW5zd2VyIjogImlkemllIiwKICAgICAgICAgICAgInRvcGljIjogInZlcmJzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiQ29uanVnYXRlICdyb2JpxIcnICh0byBkbykgZm9yICdteSciLAogICAgICAgICAgICAiYW5zd2VyIjogInJvYmlteSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2ZXJicyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkNvbmp1Z2F0ZSAnd2llZHppZcSHJyAodG8ga25vdykgZm9yICd3eSciLAogICAgICAgICAgICAiYW5zd2VyIjogIndpZWNpZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2ZXJicyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkNvbmp1Z2F0ZSAnY2hjaWXEhycgKHRvIHdhbnQpIGZvciAnb25pJyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiY2hjxIUiLAogICAgICAgICAgICAidG9waWMiOiAidmVyYnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJDb25qdWdhdGUgJ23Ds2MnIChjYW4pIGZvciAnamEnIiwKICAgICAgICAgICAgImFuc3dlciI6ICJtb2fEmSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2ZXJicyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkNvbmp1Z2F0ZSAnbXVzaWXEhycgKG11c3QpIGZvciAndHknIiwKICAgICAgICAgICAgImFuc3dlciI6ICJtdXNpc3oiLAogICAgICAgICAgICAidG9waWMiOiAidmVyYnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJDb25qdWdhdGUgJ2plxZvEhycgKHRvIGVhdCkgZm9yICdvbmEnIiwKICAgICAgICAgICAgImFuc3dlciI6ICJqZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ2ZXJicyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkNvbmp1Z2F0ZSAncGnEhycgKHRvIGRyaW5rKSBmb3IgJ215JyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicGlqZW15IiwKICAgICAgICAgICAgInRvcGljIjogInZlcmJzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiQ29uanVnYXRlICdzcGHEhycgKHRvIHNsZWVwKSBmb3IgJ2phJyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAixZtwacSZIiwKICAgICAgICAgICAgInRvcGljIjogInZlcmJzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiQ29uanVnYXRlICdjenl0YcSHJyAodG8gcmVhZCkgZm9yICd0eSciLAogICAgICAgICAgICAiYW5zd2VyIjogImN6eXRhc3oiLAogICAgICAgICAgICAidG9waWMiOiAidmVyYnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJDb25qdWdhdGUgJ3Bpc2HEhycgKHRvIHdyaXRlKSBmb3IgJ29uJyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicGlzemUiLAogICAgICAgICAgICAidG9waWMiOiAidmVyYnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJDb25qdWdhdGUgJ23Ds3dpxIcnICh0byBzcGVhaykgZm9yICdteSciLAogICAgICAgICAgICAiYW5zd2VyIjogIm3Ds3dpbXkiLAogICAgICAgICAgICAidG9waWMiOiAidmVyYnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJDb25qdWdhdGUgJ3VjennEhyBzacSZJyAodG8gbGVhcm4pIGZvciAnamEnIiwKICAgICAgICAgICAgImFuc3dlciI6ICJ1Y3rEmSBzacSZIiwKICAgICAgICAgICAgInRvcGljIjogInZlcmJzIgogICAgICAgIH0KICAgIF0sCiAgICAicHJvbm91bnMiOiBbCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiV2hhdCBpcyAnSScgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiamEiLAogICAgICAgICAgICAidG9waWMiOiAicHJvbm91bnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXaGF0IGlzICd5b3UnIChpbmZvcm1hbCkgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAidHkiLAogICAgICAgICAgICAidG9waWMiOiAicHJvbm91bnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXaGF0IGlzICdoZScgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAib24iLAogICAgICAgICAgICAidG9waWMiOiAicHJvbm91bnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXaGF0IGlzICdzaGUnIGluIFBvbGlzaD8iLAogICAgICAgICAgICAiYW5zd2VyIjogIm9uYSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcm9ub3VucyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldoYXQgaXMgJ3dlJyBpbiBQb2xpc2g/IiwKICAgICAgICAgICAgImFuc3dlciI6ICJteSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcm9ub3VucyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIldoYXQgaXMgJ3lvdScgKHBsdXJhbC9mb3JtYWwpIGluIFBvbGlzaD8iLAogICAgICAgICAgICAiYW5zd2VyIjogInd5IiwKICAgICAgICAgICAgInRvcGljIjogInByb25vdW5zIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiV2hhdCBpcyAndGhleScgKG1hc2N1bGluZSkgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAib25pIiwKICAgICAgICAgICAgInRvcGljIjogInByb25vdW5zIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiV2hhdCBpcyAndGhleScgKGZlbWluaW5lKSBpbiBQb2xpc2g/IiwKICAgICAgICAgICAgImFuc3dlciI6ICJvbmUiLAogICAgICAgICAgICAidG9waWMiOiAicHJvbm91bnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJXaGF0IGlzICdpdCcgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAib25vIiwKICAgICAgICAgICAgInRvcGljIjogInByb25vdW5zIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdteScgKHBvc3Nlc3NpdmUpIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibcOzaiIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcm9ub3VucyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAneW91cicgKGluZm9ybWFsKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInR3w7NqIiwKICAgICAgICAgICAgInRvcGljIjogInByb25vdW5zIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdvdXInIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibmFzeiIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcm9ub3VucyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAndGhlaXInIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiaWNoIiwKICAgICAgICAgICAgInRvcGljIjogInByb25vdW5zIgogICAgICAgIH0KICAgIF0sCiAgICAiYWRqZWN0aXZlcyI6IFsKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2JpZycgKG1hc2N1bGluZSkgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJkdcW8eSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJhZGplY3RpdmVzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdzbWFsbCcgKG1hc2N1bGluZSkgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJtYcWCeSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJhZGplY3RpdmVzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdnb29kJyAobWFzY3VsaW5lKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogImRvYnJ5IiwKICAgICAgICAgICAgInRvcGljIjogImFkamVjdGl2ZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2JhZCcgKG1hc2N1bGluZSkgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJ6xYJ5IiwKICAgICAgICAgICAgInRvcGljIjogImFkamVjdGl2ZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2JlYXV0aWZ1bCcgKGZlbWluaW5lKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInBpxJlrbmEiLAogICAgICAgICAgICAidG9waWMiOiAiYWRqZWN0aXZlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnbmV3JyAobWFzY3VsaW5lKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogIm5vd3kiLAogICAgICAgICAgICAidG9waWMiOiAiYWRqZWN0aXZlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnb2xkJyAobWFzY3VsaW5lKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInN0YXJ5IiwKICAgICAgICAgICAgInRvcGljIjogImFkamVjdGl2ZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3lvdW5nJyAobWFzY3VsaW5lKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogIm3Fgm9keSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJhZGplY3RpdmVzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdoYXBweScgKG1hc2N1bGluZSkgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJzemN6xJnFm2xpd3kiLAogICAgICAgICAgICAidG9waWMiOiAiYWRqZWN0aXZlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnc2FkJyAobWFzY3VsaW5lKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInNtdXRueSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJhZGplY3RpdmVzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdob3QnIChtYXNjdWxpbmUpIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZ29yxIVjeSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJhZGplY3RpdmVzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdjb2xkJyAobWFzY3VsaW5lKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInppbW55IiwKICAgICAgICAgICAgInRvcGljIjogImFkamVjdGl2ZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2Zhc3QnIChtYXNjdWxpbmUpIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAic3p5YmtpIiwKICAgICAgICAgICAgInRvcGljIjogImFkamVjdGl2ZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3Nsb3cnIChtYXNjdWxpbmUpIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAid29sbnkiLAogICAgICAgICAgICAidG9waWMiOiAiYWRqZWN0aXZlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnZWFzeScgKG1hc2N1bGluZSkgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICLFgmF0d3kiLAogICAgICAgICAgICAidG9waWMiOiAiYWRqZWN0aXZlcyIKICAgICAgICB9CiAgICBdLAogICAgInBocmFzZXMiOiBbCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiSG93IGRvIHlvdSBzYXkgJ0hlbGxvJyBpbiBQb2xpc2g/IiwKICAgICAgICAgICAgImFuc3dlciI6ICJjemXFm8SHIiwKICAgICAgICAgICAgInRvcGljIjogInBocmFzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJIb3cgZG8geW91IHNheSAnR29vZGJ5ZScgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZG8gd2lkemVuaWEiLAogICAgICAgICAgICAidG9waWMiOiAicGhyYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkhvdyBkbyB5b3Ugc2F5ICdQbGVhc2UnIGluIFBvbGlzaD8iLAogICAgICAgICAgICAiYW5zd2VyIjogInByb3N6xJkiLAogICAgICAgICAgICAidG9waWMiOiAicGhyYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkhvdyBkbyB5b3Ugc2F5ICdUaGFuayB5b3UnIGluIFBvbGlzaD8iLAogICAgICAgICAgICAiYW5zd2VyIjogImR6acSZa3VqxJkiLAogICAgICAgICAgICAidG9waWMiOiAicGhyYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkhvdyBkbyB5b3Ugc2F5ICdZZXMnIGluIFBvbGlzaD8iLAogICAgICAgICAgICAiYW5zd2VyIjogInRhayIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwaHJhc2VzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiSG93IGRvIHlvdSBzYXkgJ05vJyBpbiBQb2xpc2g/IiwKICAgICAgICAgICAgImFuc3dlciI6ICJuaWUiLAogICAgICAgICAgICAidG9waWMiOiAicGhyYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkhvdyBkbyB5b3Ugc2F5ICdFeGN1c2UgbWUnIGluIFBvbGlzaD8iLAogICAgICAgICAgICAiYW5zd2VyIjogInByemVwcmFzemFtIiwKICAgICAgICAgICAgInRvcGljIjogInBocmFzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJIb3cgZG8geW91IHNheSAnSSBkb24ndCB1bmRlcnN0YW5kJyBpbiBQb2xpc2g/IiwKICAgICAgICAgICAgImFuc3dlciI6ICJuaWUgcm96dW1pZW0iLAogICAgICAgICAgICAidG9waWMiOiAicGhyYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkhvdyBkbyB5b3Ugc2F5ICdHb29kIG1vcm5pbmcnIGluIFBvbGlzaD8iLAogICAgICAgICAgICAiYW5zd2VyIjogImR6aWXFhCBkb2JyeSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwaHJhc2VzIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiSG93IGRvIHlvdSBzYXkgJ0dvb2QgbmlnaHQnIGluIFBvbGlzaD8iLAogICAgICAgICAgICAiYW5zd2VyIjogImRvYnJhbm9jIiwKICAgICAgICAgICAgInRvcGljIjogInBocmFzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJIb3cgZG8geW91IHNheSAnSG93IGFyZSB5b3U/JyBpbiBQb2xpc2g/IiwKICAgICAgICAgICAgImFuc3dlciI6ICJqYWsgc2nEmSBtYXN6IiwKICAgICAgICAgICAgInRvcGljIjogInBocmFzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJIb3cgZG8geW91IHNheSAnTXkgbmFtZSBpcy4uLicgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibmF6eXdhbSBzacSZIiwKICAgICAgICAgICAgInRvcGljIjogInBocmFzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJIb3cgZG8geW91IHNheSAnTmljZSB0byBtZWV0IHlvdScgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibWnFgm8gbWkgY2nEmSBwb3puYcSHIiwKICAgICAgICAgICAgInRvcGljIjogInBocmFzZXMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJIb3cgZG8geW91IHNheSAnSSBsb3ZlIHlvdScgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAia29jaGFtIGNpxJkiLAogICAgICAgICAgICAidG9waWMiOiAicGhyYXNlcyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIkhvdyBkbyB5b3Ugc2F5ICdIZWxwIScgaW4gUG9saXNoPyIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicG9tb2N5IiwKICAgICAgICAgICAgInRvcGljIjogInBocmFzZXMiCiAgICAgICAgfQogICAgXSwKICAgICJwcmVwb3NpdGlvbnMiOiBbCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdpbicgKGxvY2F0aW9uKSBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInciLAogICAgICAgICAgICAidG9waWMiOiAicHJlcG9zaXRpb25zIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdvbicgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJuYSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcmVwb3NpdGlvbnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3VuZGVyJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInBvZCIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcmVwb3NpdGlvbnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2Fib3ZlJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogIm5hZCIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcmVwb3NpdGlvbnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3dpdGgnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAieiIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcmVwb3NpdGlvbnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3dpdGhvdXQnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiYmV6IiwKICAgICAgICAgICAgInRvcGljIjogInByZXBvc2l0aW9ucyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAndG8nIChkaXJlY3Rpb24pIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZG8iLAogICAgICAgICAgICAidG9waWMiOiAicHJlcG9zaXRpb25zIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdmcm9tJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInoiLAogICAgICAgICAgICAidG9waWMiOiAicHJlcG9zaXRpb25zIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdmb3InIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZGxhIiwKICAgICAgICAgICAgInRvcGljIjogInByZXBvc2l0aW9ucyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnYWJvdXQnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibyIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcmVwb3NpdGlvbnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2JlZm9yZScgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwcnplZCIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJwcmVwb3NpdGlvbnMiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2FmdGVyJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInBvIiwKICAgICAgICAgICAgInRvcGljIjogInByZXBvc2l0aW9ucyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnYmV0d2VlbicgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJtacSZZHp5IiwKICAgICAgICAgICAgInRvcGljIjogInByZXBvc2l0aW9ucyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnbmVhcicgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJwcnp5IiwKICAgICAgICAgICAgInRvcGljIjogInByZXBvc2l0aW9ucyIKICAgICAgICB9CiAgICBdLAogICAgImZvb2QiOiBbCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdicmVhZCcgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJjaGxlYiIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJmb29kIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdtaWxrJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogIm1sZWtvIiwKICAgICAgICAgICAgInRvcGljIjogImZvb2QiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ21lYXQnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibWnEmXNvIiwKICAgICAgICAgICAgInRvcGljIjogImZvb2QiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2NoZWVzZScgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJzZXIiLAogICAgICAgICAgICAidG9waWMiOiAiZm9vZCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnYXBwbGUnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiamFixYJrbyIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJmb29kIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdlZ2cnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiamFqa28iLAogICAgICAgICAgICAidG9waWMiOiAiZm9vZCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnZmlzaCcgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJyeWJhIiwKICAgICAgICAgICAgInRvcGljIjogImZvb2QiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2NoaWNrZW4nIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAia3VyY3phayIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJmb29kIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdwb3RhdG8nIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiemllbW5pYWsiLAogICAgICAgICAgICAidG9waWMiOiAiZm9vZCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAndG9tYXRvJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInBvbWlkb3IiLAogICAgICAgICAgICAidG9waWMiOiAiZm9vZCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnY2Fycm90JyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogIm1hcmNoZXdrYSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJmb29kIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdzb3VwJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInp1cGEiLAogICAgICAgICAgICAidG9waWMiOiAiZm9vZCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnc2FsYWQnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAic2HFgmF0a2EiLAogICAgICAgICAgICAidG9waWMiOiAiZm9vZCIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAncmljZScgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJyecW8IiwKICAgICAgICAgICAgInRvcGljIjogImZvb2QiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3Bhc3RhJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogIm1ha2Fyb24iLAogICAgICAgICAgICAidG9waWMiOiAiZm9vZCIKICAgICAgICB9CiAgICBdLAogICAgInRpbWUiOiBbCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICd0b2RheScgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJkemlzaWFqIiwKICAgICAgICAgICAgInRvcGljIjogInRpbWUiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3llc3RlcmRheScgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJ3Y3pvcmFqIiwKICAgICAgICAgICAgInRvcGljIjogInRpbWUiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3RvbW9ycm93JyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogImp1dHJvIiwKICAgICAgICAgICAgInRvcGljIjogInRpbWUiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ25vdycgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJ0ZXJheiIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ0aW1lIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdsYXRlcicgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJww7PFum5pZWoiLAogICAgICAgICAgICAidG9waWMiOiAidGltZSIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICAgInF1ZXN0aW9uIjogIlRyYW5zbGF0ZSAnYWx3YXlzJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInphd3N6ZSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ0aW1lIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICduZXZlcicgaW4gUG9saXNoIiwKICAgICAgICAgICAgImFuc3dlciI6ICJuaWdkeSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ0aW1lIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdzb21ldGltZXMnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiY3phc2FtaSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ0aW1lIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICd3ZWVrJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogInR5ZHppZcWEIiwKICAgICAgICAgICAgInRvcGljIjogInRpbWUiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ21vbnRoJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogIm1pZXNpxIVjIiwKICAgICAgICAgICAgInRvcGljIjogInRpbWUiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ3llYXInIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicm9rIiwKICAgICAgICAgICAgInRvcGljIjogInRpbWUiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ2hvdXInIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAiZ29kemluYSIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ0aW1lIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdtaW51dGUnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAibWludXRhIiwKICAgICAgICAgICAgInRvcGljIjogInRpbWUiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgICJxdWVzdGlvbiI6ICJUcmFuc2xhdGUgJ21vcm5pbmcnIGluIFBvbGlzaCIsCiAgICAgICAgICAgICJhbnN3ZXIiOiAicmFubyIsCiAgICAgICAgICAgICJ0b3BpYyI6ICJ0aW1lIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAicXVlc3Rpb24iOiAiVHJhbnNsYXRlICdldmVuaW5nJyBpbiBQb2xpc2giLAogICAgICAgICAgICAiYW5zd2VyIjogIndpZWN6w7NyIiwKICAgICAgICAgICAgInRvcGljIjogInRpbWUiCiAgICAgICAgfQogICAgXQp9";

// ==================== Exercise Decoding (UTF-8 SAFE FIX - High Compatibility) ====================
function decodeExercises() {
  try {
    // 1. Base64 decode
    const decoded = atob(ENCODED_EXERCISES);

    // 2. UTF-8 Safe Conversion: Converts corrupted ASCII bytes into correct UTF-8 percent-encoding.
    const utf8Decoded = decodeURIComponent(
      decoded
        .split("")
        .map(function (c) {
          return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
        })
        .join("")
    );

    // 3. Parse the now-clean UTF-8 JSON string
    return JSON.parse(utf8Decoded);
  } catch (error) {
    // Since the string has been fixed, this error should no longer occur
    console.error("Error decoding exercises:", error);
    return null;
  }
}

// ==================== Configuration ====================
const CONFIG = {
  DEFAULT_TIMER: 30,
  NEXT_QUESTION_DELAY: 1500,
};

// ==================== State Management ====================
const state = {
  exerciseDatabase: {},
  selectedTopics: [],
  currentQuestions: [],
  currentIndex: 0,
  score: 0,
  isQuizActive: false,
  timerInterval: null,
};

// ==================== Utility Functions ====================
const utils = {
  capitalizeFirst(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  },

  shuffleArray(array) {
    return [...array].sort(() => Math.random() - 0.5);
  },

  showError(container, message, detail = "") {
    container.innerHTML = `
            <div class="error-message">
                <p><strong>⚠️ ${message}</strong></p>
                ${detail ? `<p>${detail}</p>` : ""}
            </div>
        `;
  },

  showLoading(container, message = "Loading...") {
    container.innerHTML = `
            <div class="loading-state">
                <p>📚 ${message}</p>
            </div>
        `;
  },

  showEmptyState(container) {
    container.innerHTML = `
            <div class="empty-state">
                <p>👆 Select topics above and click "Start Practice" to begin!</p>
            </div>
        `;
  },

  getScoreEmoji(percentage) {
    if (percentage === 100) return { emoji: "🏆", message: "Perfect Score!" };
    if (percentage >= 80) return { emoji: "🌟", message: "Excellent!" };
    if (percentage >= 60) return { emoji: "👍", message: "Well done!" };
    if (percentage >= 40) return { emoji: "📚", message: "Keep practicing!" };
    return { emoji: "🎉", message: "Good effort!" };
  },
};

// ==================== Safe Modal Wrapper ====================
function safeModal(message, opts = {}) {
  if (window.PolishApp && typeof window.PolishApp.showModal === "function") {
    window.PolishApp.showModal(message, opts);
  } else {
    alert(message);
  }
}

// ==================== Exercise Loading ====================
function loadExercises() {
  const app = window.PolishApp;
  const container = document.getElementById("exerciseCard");

  try {
    utils.showLoading(container, "Loading exercises...");

    // FIX: Correctly call the decoding function
    const decodedExercises = decodeExercises();
    state.exerciseDatabase = decodedExercises;

    // Validate the loaded data
    if (!state.exerciseDatabase || typeof state.exerciseDatabase !== "object") {
      throw new Error("Invalid exercise data format");
    }

    initTopicFilters();
    utils.showEmptyState(container);

    // Fade in effect if PolishApp is available
    if (app && app.effects && app.effects.fadeIn) {
      container.style.opacity = 0;
      app.effects.fadeIn(container);
    }
  } catch (error) {
    console.error("Error loading exercises:", error);
    utils.showError(
      container,
      "Could not load exercises",
      "There was an error initializing the exercises."
    );
  }
}

// ==================== Topic Filter Management ====================
function initTopicFilters() {
  const app = window.PolishApp;
  const container = document.getElementById("topicFilters");

  if (!container) return;

  container.innerHTML = "";
  const topics = Object.keys(state.exerciseDatabase);

  if (topics.length === 0) {
    container.innerHTML = '<p style="color: #999;">No topics available</p>';
    return;
  }

  topics.forEach((topic) => {
    const exercises = state.exerciseDatabase[topic];
    const count = Array.isArray(exercises) ? exercises.length : 0;

    const filterOption = createFilterOption(topic, count);
    container.appendChild(filterOption);
  });
}

function createFilterOption(topic, count) {
  const app = window.PolishApp;
  const div = document.createElement("div");
  div.className = "filter-option";
  div.innerHTML = `
        <input type="checkbox" id="topic-${topic}" value="${topic}">
        <label for="topic-${topic}">${utils.capitalizeFirst(topic)}</label>
        <span class="count-badge">${count}</span>
    `;

  const checkbox = div.querySelector("input");

  // Click anywhere on the option to toggle
  const clickHandler = (e) => {
    if (e.target.tagName !== "INPUT") {
      checkbox.checked = !checkbox.checked;
      checkbox.dispatchEvent(new Event("change"));
    }
  };

  // Handle checkbox change
  const changeHandler = (e) => {
    div.classList.toggle("active", e.target.checked);
    updateSelectedTopics();
  };

  // Use PolishApp DOM utilities if available
  if (app && app.dom && app.dom.addEvent) {
    app.dom.addEvent(div, "click", clickHandler);
    app.dom.addEvent(checkbox, "change", changeHandler);
  } else {
    div.addEventListener("click", clickHandler);
    checkbox.addEventListener("change", changeHandler);
  }

  return div;
}

function updateSelectedTopics() {
  const checkboxes = document.querySelectorAll(
    '#topicFilters input[type="checkbox"]'
  );
  state.selectedTopics = Array.from(checkboxes)
    .filter((cb) => cb.checked)
    .map((cb) => cb.value);

  const startBtn = document.getElementById("startBtn");
  if (startBtn) {
    startBtn.disabled = state.selectedTopics.length === 0 || state.isQuizActive;
  }
}

// ==================== Quiz Management ====================
function startPractice() {
  // Gather questions from selected topics
  state.currentQuestions = [];

  state.selectedTopics.forEach((topic) => {
    const exercises = state.exerciseDatabase[topic];
    if (Array.isArray(exercises)) {
      state.currentQuestions.push(...exercises);
    }
  });

  if (state.currentQuestions.length === 0) {
    safeModal("Please select at least one topic!");
    return;
  }

  // Shuffle if enabled
  const shuffleToggle = document.getElementById("shuffleToggle");
  if (shuffleToggle && shuffleToggle.checked) {
    state.currentQuestions = utils.shuffleArray(state.currentQuestions);
  }

  // Reset quiz state
  state.currentIndex = 0;
  state.score = 0;
  state.isQuizActive = true;

  // Update UI
  const startBtn = document.getElementById("startBtn");
  const resetBtn = document.getElementById("resetBtn");

  if (startBtn) startBtn.style.display = "none";
  if (resetBtn) resetBtn.style.display = "inline-block";

  // Disable topic selection during quiz
  disableTopicSelection(true);

  showQuestion();
}

function resetQuiz() {
  clearInterval(state.timerInterval);

  // Reset state
  state.isQuizActive = false;
  state.currentIndex = 0;
  state.score = 0;
  state.currentQuestions = [];

  // Update UI
  const startBtn = document.getElementById("startBtn");
  const resetBtn = document.getElementById("resetBtn");
  const progressFill = document.getElementById("progressFill");
  const container = document.getElementById("exerciseCard");

  if (startBtn) startBtn.style.display = "inline-block";
  if (resetBtn) resetBtn.style.display = "none";
  if (progressFill) progressFill.style.width = "0%";

  // Re-enable topic selection
  disableTopicSelection(false);

  if (container) {
    utils.showEmptyState(container);
  }

  updateSelectedTopics();
}

function disableTopicSelection(disabled) {
  const checkboxes = document.querySelectorAll("#topicFilters input");
  const filterOptions = document.querySelectorAll(".filter-option");

  checkboxes.forEach((cb) => (cb.disabled = disabled));
  filterOptions.forEach((opt) => (opt.style.opacity = disabled ? "0.6" : "1"));
}

// ==================== Question Display ====================
function showQuestion() {
  const app = window.PolishApp;
  clearInterval(state.timerInterval);

  const container = document.getElementById("exerciseCard");
  const question = state.currentQuestions[state.currentIndex];

  // Check if quiz is complete
  if (!question) {
    showFinalScore();
    return;
  }

  updateProgress();

  // Build question HTML
  container.innerHTML = `
        <div class="question-number">Question ${state.currentIndex + 1} of ${
    state.currentQuestions.length
  }</div>
        <div class="topic-tag">${utils.capitalizeFirst(question.topic)}</div>
        <div class="question-text">${question.question}</div>
        <input type="text" class="answer-input" id="answerInput" placeholder="Type your answer..." autofocus>
        <button class="btn" id="checkBtn">Check Answer</button>
        <div id="resultMessage"></div>
        <div class="score-display">Score: ${state.score} / ${
    state.currentIndex
  }</div>
        <div class="timer-display" id="timerDisplay"></div>
    `;

  // Fade in effect using PolishApp if available
  if (app && app.effects && app.effects.fadeIn) {
    container.style.opacity = 0;
    app.effects.fadeIn(container);
  }

  // Attach event listeners
  const checkBtn = document.getElementById("checkBtn");
  const answerInput = document.getElementById("answerInput");

  if (checkBtn) {
    if (app && app.dom && app.dom.addEvent) {
      app.dom.addEvent(checkBtn, "click", checkAnswer);
    } else {
      checkBtn.addEventListener("click", checkAnswer);
    }
  }

  if (answerInput) {
    const enterHandler = (e) => {
      if (e.key === "Enter") checkAnswer();
    };

    if (app && app.dom && app.dom.addEvent) {
      app.dom.addEvent(answerInput, "keypress", enterHandler);
    } else {
      answerInput.addEventListener("keypress", enterHandler);
    }
  }

  startTimer();
}

// ==================== Timer Management ====================
function startTimer() {
  clearInterval(state.timerInterval);

  const timerSelect = document.getElementById("timerSelect");
  let timeLeft = timerSelect
    ? parseInt(timerSelect.value)
    : CONFIG.DEFAULT_TIMER;

  if (timeLeft === 0) return; // No timer

  const display = document.getElementById("timerDisplay");
  if (!display) return;

  display.textContent = `⏱️ Time: ${timeLeft}s`;

  state.timerInterval = setInterval(() => {
    timeLeft--;
    display.textContent = `⏱️ Time: ${timeLeft}s`;

    if (timeLeft <= 0) {
      clearInterval(state.timerInterval);
      showResult(false, true);
    }
  }, 1000);
}

// ==================== Answer Checking ====================
function checkAnswer() {
  clearInterval(state.timerInterval);

  const answerInput = document.getElementById("answerInput");
  if (!answerInput) return;

  const userAnswer = answerInput.value.trim().toLowerCase();
  const question = state.currentQuestions[state.currentIndex];
  const correctAnswer = question.answer.toLowerCase();

  const isCorrect = userAnswer === correctAnswer;
  if (isCorrect) state.score++;

  showResult(isCorrect, false);
}

function showResult(isCorrect, timeUp) {
  const question = state.currentQuestions[state.currentIndex];
  const resultDiv = document.getElementById("resultMessage");
  const checkBtn = document.getElementById("checkBtn");
  const answerInput = document.getElementById("answerInput");

  if (!resultDiv || !checkBtn || !answerInput) return;

  // Disable input
  answerInput.disabled = true;

  // Show result message
  if (timeUp) {
    resultDiv.innerHTML = `
            <div class="result-message result-incorrect">
                ⏰ Time's up! Correct answer: <strong>${question.answer}</strong>
            </div>
        `;
  } else if (isCorrect) {
    resultDiv.innerHTML = `
            <div class="result-message result-correct">✅ Correct!</div>
        `;
  } else {
    resultDiv.innerHTML = `
            <div class="result-message result-incorrect">
                ❌ Incorrect. Correct answer: <strong>${question.answer}</strong>
            </div>
        `;
  }

  // Change button to "Next Question"
  checkBtn.textContent = "Next Question";
  checkBtn.onclick = nextQuestion;
}

function nextQuestion() {
  state.currentIndex++;
  setTimeout(() => showQuestion(), CONFIG.NEXT_QUESTION_DELAY);
}

// ==================== Final Score Display ====================
function showFinalScore() {
  const app = window.PolishApp;
  const container = document.getElementById("exerciseCard");
  if (!container) return;

  const percentage = Math.round(
    (state.score / state.currentQuestions.length) * 100
  );
  const { emoji, message } = utils.getScoreEmoji(percentage);

  container.innerHTML = `
        <div style="animation: fadeIn 0.8s ease;">
            <div style="font-size: 4rem; margin-bottom: 20px;">${emoji}</div>
            <h2 style="color: #c61322; margin-bottom: 15px;">${message}</h2>
            <div class="final-score">${state.score} / ${state.currentQuestions.length}</div>
            <div style="font-size: 1.3rem; color: #666; margin-bottom: 30px;">${percentage}% Correct</div>
            <button class="btn" onclick="resetQuiz()">Practice Again</button>
        </div>
    `;

  // Fade in effect using PolishApp if available
  if (app && app.effects && app.effects.fadeIn) {
    container.style.opacity = 0;
    app.effects.fadeIn(container);
  }

  updateProgress(true);
  state.isQuizActive = false;
}

// ==================== Progress Bar ====================
function updateProgress(complete = false) {
  const progressFill = document.getElementById("progressFill");
  if (!progressFill) return;

  if (complete) {
    progressFill.style.width = "100%";
  } else {
    const percentage =
      (state.currentIndex / state.currentQuestions.length) * 100;
    progressFill.style.width = percentage + "%";
  }
}

// ==================== Initialization ====================
function init() {
  const app = window.PolishApp;

  // Wait for PolishApp if it's not ready yet
  if (!app || !app.dom) {
    return setTimeout(init, 40);
  }

  const { dom } = app;

  // Wait for DOM ready
  dom.onReady(() => {
    // Load exercises
    loadExercises();

    // Attach event listeners using PolishApp utilities
    const startBtn = dom.qs("#startBtn");
    const resetBtn = dom.qs("#resetBtn");

    if (startBtn) {
      dom.addEvent(startBtn, "click", startPractice);
      startBtn.disabled = true;
    }

    if (resetBtn) {
      dom.addEvent(resetBtn, "click", resetQuiz);
    }
  });
}

// Start initialization
init();

// Expose functions to global scope for compatibility
window.resetQuiz = resetQuiz;
window.startPractice = startPractice;
